name = "Indicators"
uuid = "70c4c096-89a6-5ec6-8236-da8aa3bd86fd"
authors = ["Jacob Amos <jamos125@gmail.com>"]
version = "0.9.0-DEV"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Temporal = "a110ec8f-48c8-5d59-8f7e-f91bc4cc0c3d"

[weakdeps]
Temporal = "a110ec8f-48c8-5d59-8f7e-f91bc4cc0c3d"

[extensions]
IndicatorsTemporalExt = "Temporal"

[compat]
Temporal = "^0.8"
julia = "^1.2"
